### ISSUE TITLE
TLS handshake error from 127.0.0.1:57977: local error: tls: bad record MAC

### ISSUE THREAD

**Issue by brownchow** [tomarrell/miniqueue#3]
Hi tomarrell:

I just clone the repository, and run the following:

1. build the exetutable in the root directory
```sh
go build .
```
2.  start the server
```sh
./miniqueue.exe --human
```
3. publish a message to a topic using curl
```sh
curl -X POST https://localhost:8080/publish/foo --data "helloworld"
```

the server produce:
```sh
2021/02/19 19:28:17 http: TLS handshake error from 127.0.0.1:57977: local error: tls: bad record MAC
```
and  curl produce:
```sh
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

the [echo](https://github.com/tomarrell/miniqueue/tree/master/examples/echo) example has similar problem.

maybe I should create a certificate on my own, and try again?

I'm using Windows10 and git-bash

**Comment by tomarrell** [comment]
Hey @brownchow, thanks for the issue. It looks like you are running miniqueue with the default cert and key, which won't be trusted by a certificate authority on your machine by default.

I would recommend you generate your own certs and pass them in using the specified flags. You can use the [mkcert](https://github.com/FiloSottile/mkcert) tool to quickly and easily do this for testing purposes.

```bash
$ mkcert -install
$ mkcert localhost
```

You can then cert and key files in the `/testdata` directory with your own.

If you don't want to jump through those hoops, you can ask specify the `-k` flag with curl to ignore TLS. However I would not recommend this approach.

**Comment by brownchow** [comment]
> Hey @brownchow, thanks for the issue. It looks like you are running miniqueue with the default cert and key, which won't be trusted by a certificate authority on your machine by default.
> 
> I would recommend you generate your own certs and pass them in using the specified flags. You can use the [mkcert](https://github.com/FiloSottile/mkcert) tool to quickly and easily do this for testing purposes.
> 
> ```shell
> $ mkcert -install
> $ mkcert localhost
> ```
> 
> You can then cert and key files in the `/testdata` directory with your own.
> 
> If you don't want to jump through those hoops, you can ask specify the `-k` flag with curl to ignore TLS. However I would not recommend this approach.

great, this works for me, thanks!
